### ISSUE TITLE
Need help for GLTFLoader scene 

### ISSUE THREAD

**Issue by quangArchiviet** [Brakebein/node-three-gltf#3]
Hi,

Thank you for sharing a great library.

I am new to ThreeJS. And I was having trouble using GLTFLoader.

I used `useGLTF` (@react-three/drei). But it seems that the `useGLTF scene` and the `GLTFLoader scene` are different.

I can't use GLTFLoader's scene to render with `<primitive object={model.scene} />`.

Where did I go wrong? Or is it wrong to use primitive in this case?

Thank you so much.

This is GLTFLoader scene:
<img width="324" alt="Screen Shot 2022-10-01 at 23 52 17" src="https://user-images.githubusercontent.com/68496597/193419834-a5f4a2f8-3b37-44ed-96f0-b99e3b563295.png">

And this is useGLTF scene:
<img width="333" alt="Screen Shot 2022-10-01 at 23 52 32" src="https://user-images.githubusercontent.com/68496597/193419846-53192b74-d2a6-4021-82b6-d0b8d5434520.png">

**Comment by Brakebein** [comment]
This library is intended to be used in a Node.js environment. In a browser environment you can just use the original [GLTFLoader](https://threejs.org/docs/index.html?q=glt#examples/en/loaders/GLTFLoader) from three.js.

And I'm even not sure if you are actually using this library, because your log of the "GLTFLoader scene" looks like [JSON Object Scene format](https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4) (a format you can use with [ObjectLoader](https://threejs.org/docs/index.html?q=object#api/en/loaders/ObjectLoader)). Nothing what the GLTFLoader from three.js or the adapted version from this library outputs.

Apart from that I have to say that I'm not familiar with `@react-three/fiber` or `@react-three/drei`, but as I understand it after a 5 minute research: `useGLTF` already utilizes GLTFLoader to load and parse a file. So, I'm not sure what you are actually trying to do.

Actually, this library souldn't work in a browser environment, since it depends on some modules specific to Node.js. So my guess is that you may have posted your issue in the wrong repository?

**Comment by quangArchiviet** [comment]
I'm sorry because I made you confused. Let me explain my problem.

I used `useGLTF (in @react-three/drei) ` to load the GLB model and use the model scene data to render the model via Threejs Canvas.

But this way, any user can see the `GLB URL in the Browser inspector`. Then, I want to hide the mode link. So I'm considering using your lib in `NodeJS API` to load the model and send the `scene, and animations` to the client side.

Below is NodeJs code:

```
try {
    const loader = new GLTFLoader();
    loader.load(url, (gltf: any) => {
      return res.status(200).json({
        scene: gltf.scene,
        animations: gltf.animations,
        error: false
      });
    });
  } catch (err) {
    return res.status(500).json({
      data: err,
      message: "Something went wrong. Please try again later",
      error: true
    });
  }
```

But, actually, I don't know how to use the scene from the API response (`node-three-gltf` lib). Because it's different from the `useGLTF` scene that I used before.

**Comment by quangArchiviet** [comment]
Humm,

When I try to log (on the backend) the responses of `node-three-gltf GLTFLoader`. It is the same with `@react-three/drei useGLTF`.

But when I return it to the front-end (only: `gltf.scene`) ... what I received on the front-end is a different thing (like bellow)

<img width="324" alt="193419834-a5f4a2f8-3b37-44ed-96f0-b99e3b563295" src="https://user-images.githubusercontent.com/68496597/193444686-57406b92-053c-42a3-b7b5-e1f3d04fb099.png">

Then, if I return the whole `gltf data`, an error will occur on the backend

```
err TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'GLTFParser'
    |     property 'plugins' -> object with constructor 'Object'
    |     property 'KHR_materials_clearcoat' -> object with constructor 'GLTFMaterialsClearcoatExtension'
    --- property 'parser' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/Users/durza/Documents/GitHub/marketplaceAPI/node_modules/express/lib/response.js:1119:12)
    at ServerResponse.json (/Users/durza/Documents/GitHub/marketplaceAPI/node_modules/express/lib/response.js:260:14)
    at /Users/durza/Documents/GitHub/marketplaceAPI/src/controllers/download.controllers.ts:196:28
    at Generator.next (<anonymous>)
    at fulfilled (/Users/durza/Documents/GitHub/marketplaceAPI/src/controllers/download.controllers.ts:5:58)

```

**Comment by Brakebein** [comment]
Ok, now I understand what you are trying to do. Well, you can't just simply send a scene object or any other three.js object from backend to frontend, because all these objects have circular dependencies (i.e. an object references multiple children via `children: [...]` property and all the children reference the object via `parent` property). So, `res.json()` is trying to convert the scene object to JSON and is obviously automatically utilizing [`scene.toJSON`](https://threejs.org/docs/index.html?q=scene#api/en/scenes/Scene.toJSON), which converts the scene into this JSON Object Scene Format as mentioned above, which has no more circular dependencies. Hence, at the frontend, you need to convert it back to a proper scene object to use it. To do so you need to use the [ObjectLoader](https://threejs.org/docs/index.html?q=object#api/en/loaders/ObjectLoader).

So, at the backend you do:

```js
return res.status(200).json({
  scene: gltf.scene.toJSON(),
  animations: gltf.animations,
  error: false
});
```

And at the frontend, you need to do something like:

```js
const scene = new ObjectLoader().parse(response.data.scene);
```

I don't know, if you need to convert the animations as well. I haven't done anything with animations yet.

**Comment by quangArchiviet** [comment]
You are right!

The scene has the same format as [JSON Object Scene format 4](https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4).

I tried your suggestion and got another error
<img width="726" alt="Screen Shot 2022-10-02 at 18 57 57" src="https://user-images.githubusercontent.com/68496597/193452778-0696006c-b16f-48dd-a771-3c67fbd79726.png">
<img width="462" alt="Screen Shot 2022-10-02 at 18 58 39" src="https://user-images.githubusercontent.com/68496597/193452808-92701cfd-ba25-46ce-a325-74655d6ca829.png">

I've Googled it and haven't seen anyone with the same error.  😩

**Comment by quangArchiviet** [comment]
Found the problem. ObjectLoader has a problem with textures images.
